bundler_args: ""
before_script: mysql -uroot -e 'create database after_commit_exception_notification'
rvm:
  - 2.2.7
  - 2.3.4
  - 2.4.1
gemfile:
 - gemfiles/rails3.2.gemfile
 - gemfiles/rails4.2.gemfile
